# app/helpers/application_helper.rb
module ApplicationHelper
    def currencies_data
      [
        { n: "US Dollar", c: "USD", s: "$", i: "us" },
        { n: "Euro", c: "EUR", s: "€", i: "eu" },
        { n: "British Pound", c: "GBP", s: "£", i: "gb" },
        { n: "Georgian Lari", c: "GEL", s: "₾", i: "ge" },
        { n: "Japanese Yen", c: "JPY", s: "¥", i: "jp" },
        { n: "Australian Dollar", c: "AUD", s: "A$", i: "au" },
        { n: "Canadian Dollar", c: "CAD", s: "C$", i: "ca" },
        { n: "Swiss Franc", c: "CHF", s: "Fr", i: "ch" },
        { n: "Chinese Yuan", c: "CNY", s: "¥", i: "cn" },
        { n: "Indian Rupee", c: "INR", s: "₹", i: "in" },
        { n: "Turkish Lira", c: "TRY", s: "₺", i: "tr" },
        { n: "UAE Dirham", c: "AED", s: "د.إ", i: "ae" },
        { n: "Israeli Shekel", c: "ILS", s: "₪", i: "il" },
        { n: "Swedish Krona", c: "SEK", s: "kr", i: "se" },
        { n: "Brazilian Real", c: "BRL", s: "R$", i: "br" },
        { n: "Mexican Peso", c: "MXN", s: "$", i: "mx" },
        { n: "Afghan Afghani", c: "AFN", s: "Af", i: "af" },
        { n: "Albanian Lek", c: "ALL", s: "L", i: "al" },
        { n: "Armenian Dram", c: "AMD", s: "֏", i: "am" },
        { n: "Angolan Kwanza", c: "AOA", s: "Kz", i: "ao" },
        { n: "Argentine Peso", c: "ARS", s: "$", i: "ar" },
        { n: "Azerbaijani Manat", c: "AZN", s: "₼", i: "az" },
        { n: "Bangladeshi Taka", c: "BDT", s: "৳", i: "bd" },
        { n: "Bulgarian Lev", c: "BGN", s: "лв", i: "bg" },
        { n: "Bahraini Dinar", c: "BHD", s: ".د.ب", i: "bh" },
        { n: "Chilean Peso", c: "CLP", s: "$", i: "cl" },
        { n: "Colombian Peso", c: "COP", s: "$", i: "co" },
        { n: "Czech Koruna", c: "CZK", s: "Kč", i: "cz" },
        { n: "Danish Krone", c: "DKK", s: "kr", i: "dk" },
        { n: "Egyptian Pound", c: "EGP", s: "E£", i: "eg" },
        { n: "Hong Kong Dollar", c: "HKD", s: "HK$", i: "hk" },
        { n: "Hungarian Forint", c: "HUF", s: "Ft", i: "hu" },
        { n: "Icelandic Króna", c: "ISK", s: "kr", i: "is" },
        { n: "Indonesian Rupiah", c: "IDR", s: "Rp", i: "id" },
        { n: "Jordanian Dinar", c: "JOD", s: "JD", i: "jo" },
        { n: "Kenyan Shilling", c: "KES", s: "KSh", i: "ke" },
        { n: "Kuwaiti Dinar", c: "KWD", s: "KD", i: "kw" },
        { n: "Kazakhstani Tenge", c: "KZT", s: "₸", i: "kz" },
        { n: "Lebanese Pound", c: "LBP", s: "L£", i: "lb" },
        { n: "Moroccan Dirham", c: "MAD", s: "DH", i: "ma" },
        { n: "Malaysian Ringgit", c: "MYR", s: "RM", i: "my" },
        { n: "Nigerian Naira", c: "NGN", s: "₦", i: "ng" },
        { n: "Norwegian Krone", c: "NOK", s: "kr", i: "no" },
        { n: "New Zealand Dollar", c: "NZD", s: "NZ$", i: "nz" },
        { n: "Omani Rial", c: "OMR", s: "RO", i: "om" },
        { n: "Philippine Peso", c: "PHP", s: "₱", i: "ph" },
        { n: "Pakistan Rupee", c: "PKR", s: "Rs", i: "pk" },
        { n: "Polish Zloty", c: "PLN", s: "zł", i: "pl" },
        { n: "Qatari Rial", c: "QAR", s: "QR", i: "qa" },
        { n: "Romanian Leu", c: "RON", s: "lei", i: "ro" },
        { n: "Saudi Riyal", c: "SAR", s: "SR", i: "sa" },
        { n: "Singapore Dollar", c: "SGD", s: "S$", i: "sg" },
        { n: "Thai Baht", c: "THB", s: "฿", i: "th" },
        { n: "Taiwan Dollar", c: "TWD", s: "NT$", i: "tw" },
        { n: "Ukrainian Hryvnia", c: "UAH", s: "₴", i: "ua" },
        { n: "Vietnamese Dong", c: "VND", s: "₫", i: "vn" },
        { n: "South African Rand", c: "ZAR", s: "R", i: "za" }
      ]
    end
  end